### ISSUE TITLE
Registration (User+Shelter)

### ISSUE THREAD

**Issue by shornbuckle** [gcivil-nyu-org/match-a-pet#1]
User Stories:

- As a Shelter employee I should be able to register on the site with reference to my concerned shelter
- As a site visitor, I should be able to create an account on the website.

Acceptance Criteria:

- Users should have unique usernames
- Users should be allowed to enter additional (but optional) details such as Profile Picture, Address, Interests, Willingness to adopt etc.
- Shelter Staff registering on the website must be be able to select the Shelter they are associated with
- Shelter details should be automatically filled if a shelter from the provided list is selected.
- Both Users and Shelter Staff should get a verification mail with a verification link to confirm registration.
- Clicking on the verification link in the verification mail should open the login page in a new tab

Definition of Done:

- Unit testing for all methods is done
- All parts needed for the acceptance criteria are functional.
- A short survey for the interface is done (at least 4 people outside the team), inputs taken, reviewed and incorporated
- Epic is completed by expected deadline
- There are zero known defects in the code or bugs
- The registration process is live on our app.

![Assignment 3 - User Story for Register Epic- Shelter](https://user-images.githubusercontent.com/65291545/94638954-0b76dd80-02a9-11eb-80c0-9ed9ed15e763.png)
![Assignment 3 - User Story for Register Epic - User](https://user-images.githubusercontent.com/65291545/94638958-0dd93780-02a9-11eb-974f-6a81308bb81c.png)

**Comment by shornbuckle** [comment]
Registration epic user story diagram was uploaded as .png.

**Comment by shornbuckle** [comment]
Acceptance Criteria:

- If users wants to use their Google or Twitter accounts to sign up, then they should be allowed to do so.
- Users should have unique usernames
- Users should be allowed to enter additional (but optional) details such as Profile Picture, Address, Interests, Willingness to adopt etc.
- Shelter Staff registering on the website must be be able to select the Shelter they are associated with
- Shelter details should be automatically filled if a shelter from the provided list is selected.
- Both Users and Shelter Staff should get a verification mail with a verification link to confirm registration.
- Clicking on the verification link in the verification mail should open the login page in a new tab

Definition of Done:

- Unit testing for all methods is done
- All parts needed for the acceptance criteria are functional.
- A short survey for the interface is done (at least 4 people outside the team), inputs taken, reviewed and incorporated
- Epic is completed by expected deadline

**Comment by shrutiagarwal28** [comment]
User Stories: 

- As a Shelter employee I should be able to register on the site with reference to my concerned shelter
- As a site visitor, I should be able to create an account on the website which will help me get a personalized feed and alerts

**Comment by shornbuckle** [comment]
A nice-to-have is if users wants to use their Google or Twitter accounts to sign up, then they can do so.
