### ISSUE TITLE
Page DoesNotExist Error while Navigating

### ISSUE THREAD

**Issue by i-rahman** [gcivil-nyu-org/match-a-pet#105]
## Expected Behavior
Clicked on a clickable link to [ShelterName] on Pet Profile expected page to Navigate to shelter page. {Home>Pets>[ShelterName] }

## Current Behavior
Clicked on a clickable link to [ShelterName] on Pet Profile and the site crashed. Got "DoesNotExist at /profile/516/" Error

## Ideas for Improvement
Do not display "Home>Pets>[ShelterName]" to users on the Pet Profile if the page is not there

## Steps to Reproduce

1. Open match-a-pet
2. Navigate to Pet page
3. Click on a Pet Card to Open Pet Profile
4. Click on the Shelter Name tag on the "Home>Pets>[ShelterName]" displayed on top of the page
5. Error - DoesNotExist at /profile/[number]

## Context (Environment)

As a user I hope to have a smooth nagivation experience in a website. Hide links and navigation paths to user on the webpage that are not active. I feel the path "Home>Pets>[ShelterName]" has no added value for a user at least at this stage of the product.

**Comment by benji7890** [comment]
fixed error. Changed to .user instead of .user_id
