### ISSUE TITLE
'My Pets' page show inaccurate information

### ISSUE THREAD

**Issue by i-rahman** [gcivil-nyu-org/match-a-pet#106]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior
I registered my pet Nycpet. Expected to see only my registered pets in the My Pet page

## Current Behavior
In My Pets section, I see pets added by other users listed as my pet. 

## Ideas for Improvement
Make My Pets page user specific, by retrieving only pets that are associated with the signed in user. 
Note: Upon further investigation, it seems like My Pets page ("http://match-a-pet.herokuapp.com/user/mypets/") is a generic page rather than user specific since I can access page with out Logging In

## Steps to Reproduce

1. Log in as test4
2. Register a pet: Nycpet
3. Logout
4. Log in as irahman_petowner
5. Register a pet: civilpet
6. Logout
7. Log n as test4
8. Navigate to My Pets
9. civilpet is listed under My Pet (very misleading)

## Context (Environment)

As a user I was surprised to learn that I "own" more pets than I actually own. I should only see my own pets when I navigate to this page, since this section is called "My Pets" and not "All Registered Pets in the System".

**Comment by benji7890** [comment]
@shornbuckle

**Comment by benji7890** [comment]
fixed
