### ISSUE TITLE
Registered as Pet Owner, but labelled as a shelter in Profile

### ISSUE THREAD

**Issue by i-rahman** [gcivil-nyu-org/match-a-pet#107]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior
Expected Profile Info to display my information as a pet owner or just as a user when I register using User Registration

## Current Behavior
Profile Info displays my information as with field labels associated with a Shelter - example: Shelter Name*, 
Shelter Email* , Shelter Staff First Name*,  Shelter Staff Last Name*, etc

## Ideas for Improvement
Use conditional statements to display field labels depending on the user type. Better yet use different form templates.

## Steps to Reproduce

1. Click on User Registration link on Home page
2. Fill in the registration form (i registered as irahman_petowner)
3. Activated my Account by clicking the verification link
4. Log in to my account
5. Navigate to My Profile
6. My Information is displayed with field labels associated with Shelter

## Context (Environment)

As a user I would expect my user account type to be reflected correctly. If I am a regular user/petowner, my information should not be tagged as Shelter Information as this can be confusing. Example: I cannot tell if the accounts that were provided to us for testing are shelter or regular user accounts.

**Comment by benji7890** [comment]
fixed
