### ISSUE TITLE
Map is not Interactive

### ISSUE THREAD

**Issue by i-rahman** [gcivil-nyu-org/match-a-pet#109]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior
Clicked the pins on the map for Shelter Location and expected to get more information about the pinned shelter location

## Current Behavior
Clicked the pins on the map for Shelter Location and the pinned locations are non responsive

## Ideas for Improvement
Test before deploying

## Steps to Reproduce

1. Open match-a-pet
2. Navigate to Shelter Page 
3. Click a pin displayed on the map
4. Non responsive map

## Context (Environment)

I was trying to find a shelter location on the map in Brooklyn. Clicked one closer to the DUMBO and the map is not showing information regarding the location.
I tested in Firebox for Linux Mint version 82.0.2 (64-bit) and Google Chrome Version 86.0.4240.198(Official build)

**Comment by benji7890** [comment]
known bug.
