### ISSUE TITLE
 No Cities avalilabe for California 

### ISSUE THREAD

**Issue by i-rahman** [gcivil-nyu-org/match-a-pet#110]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior
When registering if I choose California as a state I should be able to see Cities associated with California

## Current Behavior
There aren't any cities associated with California. 

## Ideas for Improvement
Either take out California from the State Option and keep the app local to NYC OR make the City field an open text box (and maybe use auto address completion api) 

## Steps to Reproduce

1. Click on User Registration link on Home page
2. Fill the address
3. In City field has only 4 NYC boroughs, but state has California listed as an option

## Context (Environment)

For a user from California(or even NYC), the Registration form can be misleading. The application is allowing me to chose California as a state, but has a cities fixed to the 5 NYC Boroughs. 
Tested in Firebox for Linux Mint version 82.0.2 (64-bit) and Google Chrome Version 86.0.4240.198(Official build)

**Comment by benji7890** [comment]
known bug.
