### ISSUE TITLE
Adopt Now button Not working as expected

### ISSUE THREAD

**Issue by rahulgarg97** [gcivil-nyu-org/match-a-pet#111]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior

After going to a pet profile, when I click on Adopt Now button, there should be adopt functionality like adopt request

## Current Behavior

Currently, after going to a pet profile, when I click on Adopt Now button, it just goes back to the page where it shows all the pets 

## Ideas for Improvement

Some adoption functionality should be there

## Steps to Reproduce

1. Go to a pet profile
2. Click on the adopt now button
3. It just go back to the page showing all the pets
4.

## Context (Environment)

Either mention that it's not working in the testing guide or hide it for the moment or implement it the way it should have been.

**Comment by benji7890** [comment]
fixed
