### ISSUE TITLE
email link in footer redirects to nothing - can add "mailto:" or maybe convert it to text as it might give the wrong idea on hover

### ISSUE THREAD

**Issue by ronakf11** [gcivil-nyu-org/match-a-pet#112]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

Email link in footer redirects to nothing - can add "mailto:" or maybe convert it to text as it might give the wrong idea on hover

## Expected Behavior

It should either be text, or muted link or with "mailto:" or hover not as pointer.

## Current Behavior

Right now it displays property of a link but isn't one and can be misjudged by any user.

## Ideas for Improvement

You can make it either a text, or muted link or with "mailto:" or hover not as pointer.

## Steps to Reproduce

1. Just click on the dev@matchapet.org in footer section
2.
3.
4.

## Context (Environment)

It can misguide users for a link and improving this is just a part of better UX

Make it either a text, or muted link or with "mailto:" or hover not as pointer.
Along with a bit more of information regarding what users can use this for.

**Comment by ronakf11** [comment]
Grramatical error on landing page in footer section:
"Have a Question?" instead of "Have a Questions?"

**Comment by ronakf11** [comment]
Console logs an error regarding loading of favicon.
Replace the link for any favicon on cloud or have one is the local static folder.

**Comment by benji7890** [comment]
closed.
