### ISSUE TITLE
No Realtime use of map if it's not clickable or if it doesn't redirect to relevant information

### ISSUE THREAD

**Issue by ronakf11** [gcivil-nyu-org/match-a-pet#113]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

Map for shelter location is not useful unless it gives or redirects to relevant information.

## Expected Behavior

It should either have clickable markers with description for each marker and a redirect to complete information or some interactive useful behavior to user.

## Current Behavior
\
Currently it's just a static map with  shelter locations which are of no practical use to user.

## Ideas for Improvement

It should either have clickable markers with description for each marker and a redirect to complete information or some interactive useful behavior to user.

## Steps to Reproduce

1. Just check out the shelters page.
2.
3.
4.

## Context (Environment)

As a user, I found no relevant or useful information about shelters on shelters page.

Look into customizing the maps according to your needs and make it more interactive and dynamic around your data.

**Comment by benji7890** [comment]
duplicate
