### ISSUE TITLE
On the pet card, the link to shelter is not working and throws error

### ISSUE THREAD

**Issue by sesha14** [gcivil-nyu-org/match-a-pet#116]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

On the pet detail page, there is " home>>pets>>sheltername " shown on top where clicking the shelter name does not take me to the shelter page and throws not found an error.

## Expected Behavior
On clicking the shelter name it could be redirected to the shelter detail page 

## Current Behavior
Clicking the shelter name does not take me to the shelter page and throws not found an error.

## Ideas for Improvement
On clicking the shelter name it could be redirected to the shelter detail page or do not give a button functionality to them so that user cannot click on it. 

## Steps to Reproduce
1.May be adding href link to it or remove button functionality

**Comment by benji7890** [comment]
duplicate fixed.
