### ISSUE TITLE
The shelters' detail page has login/register in header despite being logged in

### ISSUE THREAD

**Issue by sesha14** [gcivil-nyu-org/match-a-pet#119]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

When a logged in user navigates to the shelter page by clicking "shelter" button in top bar, the user is redirected to shelter page but the header changes from logged in to login/register icons.

## Expected Behavior
The header should still show that the user is logged in.

## Current Behavior
When a logged in user navigates to the shelter page by clicking "shelter" button in top bar, the user is redirected to shelter page but the header changes from logged in to login/register icons.

## Ideas for Improvement
Could be a small header code change
 
## Steps to Reproduce

1. May be edit header HTML code for shelter page

**Comment by benji7890** [comment]
duplicate
