### ISSUE TITLE
Dummy pets on My Pets page of new account i created

### ISSUE THREAD

**Issue by ronakf11** [gcivil-nyu-org/match-a-pet#121]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

When i created a new account, in My pets page i already had few dummy entries which shouldn't be there.

## Expected Behavior

My pets page should have no entries unless owner of that account adds any pet(s).

## Current Behavior

Currently it has 3 dummy entries right after account creation.

## Ideas for Improvement

Clean the user my pets model to make sure no test entries are there unless new user adds any.

## Steps to Reproduce

1. Register a user account
2. Activate account and log in
3. Go to my pets page
4. there will be 3 dummy entries

## Context (Environment)

Cleaning user database for test entries can clear this error

**Comment by benji7890** [comment]
duplicate
