### ISSUE TITLE
Error thrown when trying to delete picture from profile

### ISSUE THREAD

**Issue by jgingh7** [gcivil-nyu-org/match-a-pet#126]
## Current Behavior

![image](https://user-images.githubusercontent.com/60978943/100163093-ec4c9480-2e82-11eb-8bf8-1a5304946765.png)
If i click on clear and submit, I'm thrown with this error:
![image](https://user-images.githubusercontent.com/60978943/100163114-fc647400-2e82-11eb-9ab8-13406d1e4809.png)
AND this error page persists since there is no profile image.
AND not just for profile page, but the page with profiles listed are getting "chain-reaction" errors

## Ideas for Improvement

Automatically have default picture set, if default picture field is null.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by benji7890** [comment]
duplicate
