### ISSUE TITLE
Discover Profiles button not working 

### ISSUE THREAD

**Issue by rossy312** [gcivil-nyu-org/match-a-pet#132]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

Clicking on the "Discover Profiles" button on the homepage generates an error. 

## Expected Behavior
I expected the "Discover Profiles" button to take me to the Pets page. 

## Current Behavior
I received an error message. 

## Ideas for Improvement
Make sure this button is functional.

## Steps to Reproduce
1. I logged into the site.
2. I clicked on the "Discover Profiles" button.
3. I got an error page (screenshot attached).

## Context (Environment)
I can still access Pets from the link at the top, so I might even remove this button until it's functional. 
![Screen Shot 2020-11-24 at 10 03 23 PM](https://user-images.githubusercontent.com/69653730/100178202-6ee44c80-2ea1-11eb-9247-21c6abdc249a.png)

**Comment by benji7890** [comment]
fixed
