### ISSUE TITLE
Filter by color not working

### ISSUE THREAD

**Issue by rossy312** [gcivil-nyu-org/match-a-pet#133]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

Filtering Pets by color results in pets that are white or tan being labeled as black, and zero pets being labeled as white.

## Expected Behavior
I expected for the Black color filter to generate pets that were primarily black in color, and filtering for the White color to generate pets that were primarily white in color.

## Current Behavior
A huge variety of pets (among them, many 100% tan, brown, or white) are returned when using the Black filter, while zero pets are returned when using the White filter. Please see the attached screenshots to see some of the pets returned when the Black filter is implemented
![Screen Shot 2020-11-24 at 10 15 26 PM](https://user-images.githubusercontent.com/69653730/100178749-938cf400-2ea2-11eb-8632-5b8de3492c1c.png)
![Screen Shot 2020-11-24 at 10 15 03 PM](https://user-images.githubusercontent.com/69653730/100178756-9687e480-2ea2-11eb-86eb-a7ab93383550.png)
![Screen Shot 2020-11-24 at 10 14 58 PM](https://user-images.githubusercontent.com/69653730/100178759-9982d500-2ea2-11eb-8c00-7d7577b55227.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by benji7890** [comment]
data needs to be accurate
