### ISSUE TITLE
Register as a user, but shows shelter profile in "discover profile" page.

### ISSUE THREAD

**Issue by Huanjin-Zhang** [gcivil-nyu-org/match-a-pet#134]
## Expected Behavior
It should show the user profile after clicking one user card.
 
## Current Behavior
After clicking the user card, it will redirect to the profile page which looks like a shelter profile.

## Ideas for Improvement
Maybe the URL is wrong or you need to design a user public-facing page for it.

## Steps to Reproduce
1.click "discover profile"
2.click one user card.

**Comment by benji7890** [comment]
fixed
