### ISSUE TITLE
Filter by pet name is case sensitive, which is not user friendly.

### ISSUE THREAD

**Issue by Huanjin-Zhang** [gcivil-nyu-org/match-a-pet#135]
## Expected Behavior
When I input "jordan", I'd like to see the pet named Jordan, but nothing shows.

## Current Behavior
Only if I input "Jordan", the matching result will show up, which is not user friendly.

## Ideas for Improvement
match the filter no matter what the cases are.

## Steps to Reproduce
1. input "jordan"
2. nothing shows
3.
4.

**Comment by benji7890** [comment]
duplicate
