### ISSUE TITLE
It can not access the shelter of the pets from my favorite page

### ISSUE THREAD

**Issue by Huanjin-Zhang** [gcivil-nyu-org/match-a-pet#136]
## Expected Behavior
By clicking my favorite pets, it should have the shelter what the pets belong to.

## Current Behavior
The shelter does not show up on the pet card from my favorite pets. Therefore, it can not access the shelter profile.

## Ideas for Improvement
Add one attribute on the pet card which links to the shelter profile.

## Steps to Reproduce
1. log in as a user 
2. click my favorite
3. do not have a shelter button on the pet card.

## Context (Environment)
![image](https://user-images.githubusercontent.com/55302047/100181535-7bb86e80-2ea8-11eb-9661-2c97f9f48f73.png)

**Comment by benji7890** [comment]
fixed
