### ISSUE TITLE
Filters not working as expected

### ISSUE THREAD

**Issue by joshganguly** [gcivil-nyu-org/match-a-pet#138]
Filtering by anything other than Pet color does not work at all. Pet color needs to be part of the filter always otherwise it doesn't return any results

## Expected Behavior
All the filters listed next to the Filter button should work

## Current Behavior
`http://match-a-pet.herokuapp.com/view_pets/?pet_name=&pet_breed=shepherd&pet_color=&pet_gender= 
`or 
`http://match-a-pet.herokuapp.com/view_pets/?pet_name=Liam&pet_breed=shepherd&pet_color=&pet_gender= 
`doesn't work

## Context (Environment)
User will be unable to filter without specifying the color which he/she might not know or be interested in filtering out.

**Comment by benji7890** [comment]
duplicate
