### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by joshganguly** [gcivil-nyu-org/match-a-pet#139]
The text near the 'Choose File' button on http://match-a-pet.herokuapp.com/shelter/profile/ opens the upload window

## Expected Behavior
Only clicking on the 'Choose File' should open the upload window

## Current Behavior
Clicking on the text 'Shelter Profile Picture' or 'No file chosen' opens the upload window unexpectedly

## Steps to Reproduce
1. Click on the text 'Shelter Profile Picture' or 'No file chosen' at http://match-a-pet.herokuapp.com/shelter/profile/ and the upload window opens unexpectedly

## Context (Environment)
User misclicks the text and is taken to an upload window unexpectedly

**Comment by benji7890** [comment]
Not an issue. It's an intended behavior.
