### ISSUE TITLE
Partial search or case insensitive search not possible

### ISSUE THREAD

**Issue by vinayaknatarajan** [gcivil-nyu-org/match-a-pet#140]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

For search by dog breed, I am unable to get results if I enter partial/ or lowercase letters.

## Expected Behavior

I should be able to search for pets by breed by entering the breed type in lowercase

## Current Behavior

I am unable to get results if I enter partial/ or lowercase letters.

## Ideas for Improvement

Use the ignore case function to get results.

## Steps to Reproduce

1. Go to the Pets tab on the home page
2. Type "shepherd" or "shep" and then click filter.
![Screenshot (20).png](https://images.zenhubusercontent.com/5f6e483d084e4853eaed80b4/1c48aea9-235a-45d2-b0ba-0c0ce2a0c590) 
![Screenshot (18).png](https://images.zenhubusercontent.com/5f6e483d084e4853eaed80b4/1b79c0f7-e989-4ce9-b3c2-d180186090b6)

**Comment by benji7890** [comment]
duplicate
