### ISSUE TITLE
User state information not preserved while navigating

### ISSUE THREAD

**Issue by vinayaknatarajan** [gcivil-nyu-org/match-a-pet#141]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

When a logged-in user clicks on the shelters tab, the user logged in symbol disappears, and the login tab appears

## Current Behavior

When I click the shelter tab, the username tag disappears in the navigation bar

## Steps to Reproduce

1. Go to the Login tab and sign in
2. Once logged in click on the shelters tab.
![Screenshot (27).png](https://images.zenhubusercontent.com/5f6e483d084e4853eaed80b4/7cc25d46-70f9-481f-8d61-516efb2dbc26)
3. Again click on the login tab
![Screenshot (29).png](https://images.zenhubusercontent.com/5f6e483d084e4853eaed80b4/b85f9e7f-58b2-4fe6-86d1-50438831c3ed)

**Comment by benji7890** [comment]
duplicate #119
