### ISSUE TITLE
I Registered as a User but my profile shows me as a Shelter

### ISSUE THREAD

**Issue by gauravag2207** [gcivil-nyu-org/match-a-pet#142]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

I registered as a normal user but when I open my profile, I see the fields 'Shelter Name', 'Shelter Email' etc. The same is happening with the test users.

## Expected Behavior

I should see the user profile related fields

## Current Behavior

I see the shelter profile related fields

## Steps to Reproduce

1. Login as any normal user. e.g. test5
2. Navigate to the profile page.
3. Shelter related fields are listed

![image](https://user-images.githubusercontent.com/55005259/100275363-6a617780-2f25-11eb-830a-a24d2528022b.png)

## Context (Environment)

This conveys the wrong information to the user.

**Comment by benji7890** [comment]
duplicate #107
