### ISSUE TITLE
Send message button gives an error

### ISSUE THREAD

**Issue by gauravag2207** [gcivil-nyu-org/match-a-pet#143]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

After logging as any user, if I send a message, i get an error page

## Expected Behavior

I should be able to send a message

## Current Behavior

It throws an error

## Steps to Reproduce

1. Login as a User or Shelter
2. Goto Inbox
3. Type a message and hit send
4. Throws an error
![image](https://user-images.githubusercontent.com/55005259/100275711-fbd0e980-2f25-11eb-8e05-c8db62922279.png)

**Comment by benji7890** [comment]
fixed
