### ISSUE TITLE
Link on the breadcrumb on pet details page give error

### ISSUE THREAD

**Issue by gauravag2207** [gcivil-nyu-org/match-a-pet#144]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

If I click on the link on breadcrumb on the pets page, I get an error

## Expected Behavior

I should not get an error

## Current Behavior

It throws an error
## Steps to Reproduce

1. Login as Normal user
2. Click on a pet and Navigate to the pet details page. suppose 'Liam'
3. Click on the last link on the breadcrumb
![image](https://user-images.githubusercontent.com/55005259/100278604-c8dd2480-2f2a-11eb-8399-1bf817dd538b.png)

4. It throws an error

![image](https://user-images.githubusercontent.com/55005259/100278663-e01c1200-2f2a-11eb-9d85-bb09cdda1240.png)

**Comment by benji7890** [comment]
fixed
