### ISSUE TITLE
As a user I can message my self.

### ISSUE THREAD

**Issue by gauravag2207** [gcivil-nyu-org/match-a-pet#145]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

As a user, I can message myself by changing the URL

## Expected Behavior

A user should not be able to play with the URL and message him/her self

## Current Behavior

As a user, I can message myself by changing the URL

## Steps to Reproduce

1. Login as test2 and Navigate to the inbox
2. Add the Username at the end of the URL. E.g.'http://match-a-pet.herokuapp.com/inbox/test2'
3. Send a message. You would see 2 messages each time you send a message to yourself.

![image](https://user-images.githubusercontent.com/55005259/100280574-03948c00-2f2e-11eb-8946-f7892915ca77.png)

**Comment by benji7890** [comment]
Not going to fix. For example: Slack can message oneself as well. It's good for taking notes!
