### ISSUE TITLE
As a shelter, I can favorite a pet but don't have my favorite pets page

### ISSUE THREAD

**Issue by gauravag2207** [gcivil-nyu-org/match-a-pet#146]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

As a shelter, I can favorite a pet but don't have my favorite pets page

## Expected Behavior

I should see the favorites page

## Current Behavior

I don't see the favorites page

## Steps to Reproduce

1. Login as a shelter, say 'test2'
2. Don't have the favorites page but can favorite pets on the pet detail page

## Context (Environment)

I can't see my favorite pets as a single place

**Comment by benji7890** [comment]
duplicate #131
