### ISSUE TITLE
I can access the login and register page even when I am already logged in

### ISSUE THREAD

**Issue by gauravag2207** [gcivil-nyu-org/match-a-pet#148]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

I can access the login page even when I am already logged in

## Expected Behavior

I shouldn't be able to access the login/register page if I am already logged in.

## Current Behavior

Able to access login and register page and able to register or login with a different user
## Steps to Reproduce

1. Login as a user suppose 'test2'
2. Change the URL to 'http://match-a-pet.herokuapp.com/login/'  or 'http://match-a-pet.herokuapp.com/user/register/'
3. If you enter login url, you would see one more login page and can log in as another user
![image](https://user-images.githubusercontent.com/55005259/100281425-823df900-2f2f-11eb-9aac-b8b53bc4c94a.png)

4. If you enter register url, you would see a new registration page and can register again.
![image](https://user-images.githubusercontent.com/55005259/100281589-d0eb9300-2f2f-11eb-80f0-562f92afdea2.png)

![image](https://user-images.githubusercontent.com/55005259/100281956-6e46c700-2f30-11eb-9387-1227ad89bddf.png)

## Context (Environment)

This will allow users to login in mutiple sessions without logging out of the previous one. So there would be huge number of open connections in the backend

**Comment by benji7890** [comment]
duplicate #128
