### ISSUE TITLE
The shelter page shows login and register button for a logged in user

### ISSUE THREAD

**Issue by gauravag2207** [gcivil-nyu-org/match-a-pet#149]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

The shelter page shows login and register button for a logged-in user

## Expected Behavior

Logged in user should not see Login and register button.

## Current Behavior

After logging in, if I open shelters page, I see login and register buttons again and they work as if I am not logged in

## Ideas for Improvement

In your Django views, you may check for the condition  'user.is_authenticated' and redirect based on it.

## Steps to Reproduce

1. Login as a user
2. Navigate to the shelters page.
![image](https://user-images.githubusercontent.com/55005259/100282390-1eb4cb00-2f31-11eb-9aa3-20f19ad90253.png)
3. I can login/register again by clicking on the corresponding button
![image](https://user-images.githubusercontent.com/55005259/100282448-3a1fd600-2f31-11eb-8acf-fdff4170bbf1.png)

## Context (Environment)

I can create multiple login sessions without closing the last one.

**Comment by benji7890** [comment]
duplicate #119
