### ISSUE TITLE
My pets page doesn't show the picture of pets and also doesn't allow to click

### ISSUE THREAD

**Issue by gauravag2207** [gcivil-nyu-org/match-a-pet#150]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

My pets page doesn't show the picture of pets and also doesn't allow to click. I registered a new pet and gave a photo of it but it doesn't show

## Expected Behavior

It should show the photo

## Current Behavior

It doesn't show the photo and doesn't allow to see the details.

## Steps to Reproduce

1. Login as a user 'test5'
2. Register a pet and provide a photo.
3. Navigate to my pets page
4. No photos/link present
![image](https://user-images.githubusercontent.com/55005259/100283818-c7642a00-2f33-11eb-93fa-85499d9254fd.png)

**Comment by benji7890** [comment]
fixed
