### ISSUE TITLE
The website uses an insecure protocol http

### ISSUE THREAD

**Issue by gauravag2207** [gcivil-nyu-org/match-a-pet#153]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

The website uses an insecure protocol http.

## Current Behavior

The website uses an insecure protocol http
URL:
http://match-a-pet.herokuapp.com/

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/55005259/100286992-748d7100-2f39-11eb-897c-4b25d8022200.png)

## Context (Environment)

This can lead to multiple security issues.

**Comment by benji7890** [comment]
We're skipping this.
