### ISSUE TITLE
Site breaks when clicking on send message results in error when not logged in 

### ISSUE THREAD

**Issue by shivangpandya** [gcivil-nyu-org/match-a-pet#154]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior

When I press send message when not logged in , the web app should given me an option to redirect to login page

## Current Behavior

The site breaks and shows django error

## Ideas for Improvement

Can have a JS statement that can validate this check

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

<img width="1430" alt="Screen Shot 2020-11-25 at 5 20 36 PM" src="https://user-images.githubusercontent.com/13718156/100287686-16658b80-2f43-11eb-9ca4-f79191f0a1ab.png">

<img width="1420" alt="Screen Shot 2020-11-25 at 5 23 53 PM" src="https://user-images.githubusercontent.com/13718156/100287721-28472e80-2f43-11eb-8e25-160a525a63d6.png">

**Comment by benji7890** [comment]
Fixed.
