### ISSUE TITLE
Message error

### ISSUE THREAD

**Issue by Chuanqi927** [gcivil-nyu-org/match-a-pet#157]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

When I type something in the textbox and click on send message, it shows django error page.

## Expected Behavior

Should raise a notification for possible valid usage of this feature

## Current Behavior

Django Error page does not exist
## Steps to Reproduce

1. Click on inbox after logged in
2. Type anything in the chatbox
3. Click on send message

## Context (Environment)

I do not think this feature is well implemented because we need some kind of error handler for that

**Comment by gcivil-nyu** [comment]
This is actually totally confusing, who am I sending this message to?

+1 

<img width="1278" alt="Screen Shot 2020-11-25 at 7 24 51 PM" src="https://user-images.githubusercontent.com/53953892/100294190-fc807480-2f53-11eb-9426-d739794cf074.png">

**Comment by benji7890** [comment]
I've made it so that the message box will only appear when there's a recipient.
