### ISSUE TITLE
Already a list of pets before I register for mine

### ISSUE THREAD

**Issue by Chuanqi927** [gcivil-nyu-org/match-a-pet#158]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

After logged in, there is already a list of pets reigstered by other people in "My pets"

## Expected Behavior

There should be none before I register myself.

## Current Behavior

There are many pets already without picture profile

## Ideas for Improvement

Do not know why this happened
## Steps to Reproduce

1. Log in
2. Go to My pets 

## Context (Environment)

This is not good; it will make user confused.

**Comment by benji7890** [comment]
duplicate #106
