### ISSUE TITLE
I added a few pets to "My Favorites" but there appears to be no way to view said favorites

### ISSUE THREAD

**Issue by gcivil-nyu** [gcivil-nyu-org/match-a-pet#160]
I logged on, browsed, find a few pets to add to my favorites. Clicked on "Add to favorites" and it appeared to work, because the icon changed color  
<img width="401" alt="Screen Shot 2020-11-25 at 7 27 56 PM" src="https://user-images.githubusercontent.com/53953892/100294309-67ca4680-2f54-11eb-8c4c-1241144f9f35.png">

However I could not find a way to actually see my favorites. 

I was naively assuming that I could browse, add some pets to favorites and adapt them from there

**Comment by benji7890** [comment]
fixed. Shelters should not be able to favorite pets.
