### ISSUE TITLE
Duplicate: The search functionality is case-sensitive and the user can login/register page even while the user is logged in.

### ISSUE THREAD

**Issue by Ritukuklani** [gcivil-nyu-org/match-a-pet#161]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

The search functionality is case-sensitive.
The  user is able to access the login and registration page even while he is logged in.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by benji7890** [comment]
duplicate

**Comment by benji7890** [comment]
fixed
