### ISSUE TITLE
Creating new message as a new account and sending it (no recipient) gives an error

### ISSUE THREAD

**Issue by ponathanjun** [gcivil-nyu-org/match-a-pet#162]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior

A message should pop up and state that I have not chosen anyone to send the message to.
## Current Behavior

Redirects to error page with "DoesNotExist at /send/" and "User matching query does not exist."
## Ideas for Improvement

Instead of producing a query, maybe include a check to see if the sender has selected a recipient.
## Steps to Reproduce

1. User register and verify account
2. Click messages on the nav bar
3. Type in message and click send.

## Context (Environment)

Page gives an error that prevents me from sending messages.

**Comment by benji7890** [comment]
duplicate #118
