### ISSUE TITLE
SUGGESTION: Make emails not changeable 

### ISSUE THREAD

**Issue by ponathanjun** [gcivil-nyu-org/match-a-pet#163]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Ideas for Improvement

Defeats purpose of email verification and maybe disallow one email for multiple user accounts.
## Steps to Reproduce

1.
2.
3.
4.

**Comment by benji7890** [comment]
known issue.
