### ISSUE TITLE
Search isn't working correctly

### ISSUE THREAD

**Issue by ponathanjun** [gcivil-nyu-org/match-a-pet#167]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior

Should return results that contain said search item
## Current Behavior

Returns nothing
## Ideas for Improvement

Not too sure since searching "Shepherd" works but some other searches do not.
## Steps to Reproduce

1. User registration and login
2. Create pet with "cat" as breed
3. Go to main page and search "cat"

## Context (Environment)

Registering my pet and not having searches come up for him will make it hard for my pet to get adopted.

**Comment by benji7890** [comment]
duplicate #115
