### ISSUE TITLE
Login & Register Button in the shelters page even if users have logged in

### ISSUE THREAD

**Issue by DarkBruce** [gcivil-nyu-org/match-a-pet#168]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

After loggin in, users can still see the login and register button in the shelters page and these two buttons could still take users to the corresponding login and register page.

## Expected Behavior

No more login or register button after users logging in.

## Current Behavior

**Login** button and **Register** button are still shown in the navigation bar in the shelter page even if users have already logged in

## Ideas for Improvement

Instead of **Login** button or **Register** button, there should be a **Logout** button for users to logout.

## Steps to Reproduce

1. Login as a user;
2. Click the **Shelters** button;
3. The **Login** button and **Register** button are shown in the navigation bar in the shelters page.
4.

**Comment by benji7890** [comment]
duplicate #119
