### ISSUE TITLE
failed to send a message

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/match-a-pet#169]
I was trying to send a message for a pet that I was looking at. and got this error:

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/24606632/100296618-b4188500-2f5a-11eb-990f-b316bea9d321.png">

steps:
1. go to home page
1. click on Discover Profiles
1. click on a pet
1. click on Send a Message
1. redirected to error page

**Comment by benji7890** [comment]
duplicate 
https://github.com/gcivil-nyu-org/match-a-pet/issues/118

**Comment by jackxujh** [comment]
@benji7890 it's okay to close due to duplicate, but please also link to the original issue
