### ISSUE TITLE
map page: header inconsistency/incorrect when logged in

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/match-a-pet#171]
when logged in, go to map page and I still see login/register buttons.

https://match-a-pet.herokuapp.com/maps/shelters/

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/24606632/100297057-cf37c480-2f5b-11eb-894f-5070690bcfd0.png">

**Comment by benji7890** [comment]
duplicate #119

**Comment by jackxujh** [comment]
@benji7890 it's okay to close due to duplicate, but please also link to the original issue
