### ISSUE TITLE
Will be nice to have a "Reset Filter" button available

### ISSUE THREAD

**Issue by leelightman** [gcivil-nyu-org/match-a-pet#173]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.
![image](https://user-images.githubusercontent.com/3640558/100297156-0c9c5200-2f5c-11eb-94e6-f516ef711c2e.png)
For the Pet search page, it's a bit annoying to reset the filter. Will be nice to have a reset filter.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by benji7890** [comment]
duplicate #165
