### ISSUE TITLE
Able to access mypets page after logging out.

### ISSUE THREAD

**Issue by gsavitha** [gcivil-nyu-org/match-a-pet#174]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior
User specific pages should only be accessed by logged in users.
## Current Behavior
![image](https://user-images.githubusercontent.com/17599828/100297132-0312ea00-2f5c-11eb-9fd1-b99e6ef61f03.png)

## Ideas for Improvement
Use user authentication on all user pages.

**Comment by benji7890** [comment]
duplicate #106
