### ISSUE TITLE
The filters can't be retained after I click next page.

### ISSUE THREAD

**Issue by chenwei713** [gcivil-nyu-org/match-a-pet#177]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior

The filters should be retained if the user wants to see more pages.
## Current Behavior

filters will be reset to empty.

## Ideas for Improvement

Can be solved with ajax by avoiding reloading a new page or pass the filters to the new page.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by benji7890** [comment]
duplicate

**Comment by benji7890** [comment]
duplicate #147
