### ISSUE TITLE
Customize User model, Login, Logout, Profile Update (Shelter Registration)

### ISSUE THREAD

**Issue by benji7890** [gcivil-nyu-org/match-a-pet#35]
**User story**

As shelter staff, when I register, all of my registration data should be stored into the Match A Pet database. 

**Acceptance criteria**
When I login, I should be able to see a Welcome sign and navigation bar customized to my details.
I should only be able to update my profile when I'm logged in.
I should only be able to upload a pet profile when I'm logged in and that pet will be under my profile.

**Definition of Done**

Registration data is visible on the admin page.
User is brought to customized login website under the main home page. 
When typing homepage.com/profile, they must be logged in or be prompted to log in.
Pet profiles can only be created after logging in.

**Pointing Poker Score**

3

**Comment by gururaj3** [comment]
User story

As a shelter staff when registering, all of the fields asked in the form should be stored into the database. Perform the functionalities of login, logout, profile update for the shelter staff. 

Acceptance criteria
As a shelter staff, they must be able to login , logout, update, add pets data to the database.

Definition of Done
We were able to implement all the functionalities mentioned in the User story. 

Pointing Poker Score

3
