### ISSUE TITLE
Pet Profile Creation

### ISSUE THREAD

**Issue by benji7890** [gcivil-nyu-org/match-a-pet#36]
**User story**

- As a shelter staff, I should be able to create a profile for my pet.

**Acceptance criteria**

- If a shelter staff member wants to create a pet profile, they should be able to add in a pet to the database that is linked to their shelter by shelter_id.

**Definition of Done**

- All unit testing is done.
- Each use case is confirmed.
- The pet profiles created can be accessed.

**Pointing Poker Score**

3

**Comment by shornbuckle** [comment]
Pet profile creation has been implemented.

Still need to link the database to shelter on the foreign key "shelter_id"
